spring.datasource.url=jdbc:postgresql://localhost:5432/bus_booking_db
spring.datasource.username=postgres
spring.datasource.password=Shiva@24
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT Configuration
jwt.secret=busbooking_super_secret_key_minimum_256bits_for_hs256_algorithm_2024
jwt.expiration=86400000
